### ISSUE TITLE
Categories Multiselection not working in the cellphone version

### ISSUE THREAD

**Issue by eshelf** [Cocolabs-SAS/cocorico#143] opened 2018-02-19 16:21 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

Hi,

This is not a bug, since it works perfectly in the Cocorico demo. I'm only asking for help because I think I've tryed everithing I could possibly imagine.

In my [search page](https://www.usame.cl/en/listing/search_result), I can't select a category in the cellphone version. I have compared css and twigs but can't find what's different in my code and [cocorico](http://demo.cocorico.io/en/listing/search_result)'s master.

Do you have any suggestions about where to look in order to find my error? Any help, from anyone, would be very appreciated.

**Comment by eshelf** [comment] 2018-02-20 21:42
Hi,

Thanks for reviewing it! That error is related to google maps and only occur when the user doesn't allow to get the location automatically. I'm already handling it.

In this [link](https://www.usame.cl/en/listing/search_result?categories%5B%5D=1&location%5Baddress%5D=Quilpu%C3%A9%2C+Chile&location%5Blat%5D=-33.0482707&location%5Blng%5D=-71.4408752&location%5Bviewport%5D=%28%28-33.0781055%2C+-71.4854995%29%2C+%28-33.0255014%2C+-71.4006114%29%29&location%5Bcountry%5D=CL&location%5Barea%5D=Valparaiso+Region&location%5Bdepartment%5D=Marga+Marga&location%5Bcity%5D=Quilpu%C3%A9&location%5Bzip%5D=&location%5Broute%5D=&location%5BstreetNumber%5D=&location%5BaddressType%5D=locality%2Cpolitical&date_range%5Bstart%5D=&date_range%5Bend%5D=&price_range%5Bmin%5D=1000&price_range%5Bmax%5D=50000&characteristics%5B17%5D=&sort_by=&page=1), you'll find the same page with no errors in console, but with the same behaviour: The categories multiselect works on the desktop version but not in the responsive version.

I know it's not a bug and it's my particular problem. If you can give me any tips on where to look for errors, it will be very appreciated.

**Comment by cocolabssas** [comment] 2018-04-24 22:29
Hi we close it as it seems to be a specific custom problem difficult to simply reproduce.

**Closed by cocolabssas** 2018-04-24 22:29 UTC
Labels: help wanted
