### ISSUE TITLE
Make the Listing price optional

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#216] opened 2018-10-12 13:58 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

I've been trying to update the code by making some changes in order to make the price as "not required".

I started by updating the form `src/Cocorico/CoreBundle/Form/Type/Frontend/ListingNewType.php`
and the property `'required'` of the `'price'` field.

Then I figured that there were several constraint validators related to the price field (such as `src/Cocorico/CoreBundle/Validator/Constraints/ListingValidator.php` or others in the same directory).

However, even though I udpated all of them (the parts related to the price field), I still have the error "Required" displayed when the form is submitted.

Could you help me by pointing out the files that could be linked to that issue?

**Comment by cocolabssas** [comment] 2018-10-13 00:19
Hello @gonzasylv 

This issue is a duplicate of #197. Thanks to move your question to this issue.

**Closed by cocolabssas** 2018-10-13 00:19 UTC
Labels: help wanted
