### ISSUE TITLE
Set price to 0

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#205] opened 2018-09-22 20:26 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

There is the possibility of finishing the price when inserting an ad to 0, if yes what changes can be made?

**Comment by cocolabssas** [comment] 2018-09-24 21:45
Duplicate of #197

**Closed by cocolabssas** 2018-09-24 21:45 UTC
