### ISSUE TITLE
Search functionality is not working 

### ISSUE THREAD

**Issue by mmshivukumar** [Cocolabs-SAS/cocorico#90] opened 2017-10-16 06:25 UTC
| Support request? | yes

Dear Team,

I have installed the project in local but search function in not working may i know the solution for that ?

please help us to find solution.

Thanks in advancce
shivukumar

**Comment by kroshp** [comment] 2017-10-16 22:41
Hi,

We close it as It is a duplicate of #88

**Closed by kroshp** 2017-10-16 22:41 UTC
