### ISSUE TITLE
No characteristics available

### ISSUE THREAD

**Issue by handmade-it** [Cocolabs-SAS/cocorico#172] opened 2018-05-02 21:15 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | [X]
| Feature request? | [ ]
| Support request? | [ ]

Hi, we have created characteristics and grouped them in the admin dashboard. Nevertheless, there is no possibility to select/fill out etc. any characteristic in the listing edit screen of the dashboard. There is no interaction possibility despite the save button. 

Do I have to active something first or connect characteristics with categories?

Please give me a hint.

Thanks in advance

**Comment by cocolabssas** [comment] 2018-05-21 22:21
Hi,

We can't reproduce the problem. We can add new group and new characteristics in admin and we can change their associated values in offerer listing dashboard edition.

You don't need to associate them to categories. You only need to add through admin, characteristics 
and associate them to a characteristic group.
I suggest you to log and debug in your listing dashboard edition the available characteristics.

**Comment by handmade-it** [comment] 2018-05-24 20:21
Hi, thanks for the reply. Unfortunatelly this didn't work. I add groups and associate characteristics to them. This works and seems correct. Nevertheless, when editing offers in the dashboard, the list of available characteristics stays empty. I even started to debug your code. As far as I see, the list which is processed in the twig templates is empty.

Could you give me a hint where in your code the list of characteristics is getting compiled for the twig template? Thanks in advance. This feature is very important to us.

**Comment by cypherfunk** [comment] 2018-05-25 10:06
Hello I'm seeing the same problem but I have switched my locale to Hebrew/Israel
![image](https://user-images.githubusercontent.com/8761118/40539092-520ded42-601c-11e8-94e0-06e67577ac30.png)

when I switch back to English it seems to work.

**Comment by La-Meche** [comment] 2018-05-25 10:08
Hello @cypherfunk , can you share the Hebrew translations for the community?

**Comment by cypherfunk** [comment] 2018-05-25 10:13
will do when completed.

**Comment by handmade-it** [comment] 2018-05-25 19:58
Hi, I had been busy debugging your code and I think i found the problematic part:

The function refreshListingListingCharacteristics() in src/Cocorico/CoreBundle/Model/Manager/ListingManager.php has the following part:

//Get all characteristics
        $listingCharacteristics = new ArrayCollection(
            $listingCharacteristicRepository->findAllTranslated($listing->getCurrentLocale())
        );

This part does not provide any output when $listing->getCurrentLocale() <> "en".

When i hardcode "en" in there I get the characteristics. I've checked the backend and the database but I definitivly have translations for all characteristics and its groups

**Comment by cypherfunk** [comment] 2018-05-27 11:11
thanks for sharing. I've discovered that listingCharacteristicRepository is also empty in my case (and I'm using hebrew)
I've logged onto MariaDB and tried to debug the query that corresponds to listingCharacteristicRepository and indeed executing the following query returns 0 results:

select l0_.id AS id_0, l0_.position AS position_1, l1_.name AS name_2, l1_.description AS description_3, l1_.locale AS locale_4, l1_.id AS id_5, l2_.id AS id_6, l2_.position AS position_7, l3_.name AS name_8, l3_.locale AS locale_9, l3_.id AS id_10, l4_.id AS id_11, l4_.name AS name_12, l5_.id AS id_13, l5_.position AS position_14, l6_.name AS name_15, l6_.locale AS locale_16, l6_.id AS id_17, l0_.listing_characteristic_type_id AS listing_characteristic_type_id_18, l0_.listing_characteristic_group_id AS listing_characteristic_group_id_19, l1_.translatable_id AS translatable_id_20, l3_.translatable_id AS translatable_id_21, l5_.listing_characteristic_type_id AS listing_characteristic_type_id_22, l6_.translatable_id AS translatable_id_23 FROM listing_characteristic l0_ LEFT JOIN listing_characteristic_translation l1_ ON l0_.id = l1_.translatable_id LEFT JOIN listing_characteristic_group l2_ ON l0_.listing_characteristic_group_id = l2_.id LEFT JOIN listing_characteristic_group_translation l3_ ON l2_.id = l3_.translatable_id LEFT JOIN listing_characteristic_type l4_ ON l0_.listing_characteristic_type_id = l4_.id LEFT JOIN listing_characteristic_value l5_ ON l4_.id = l5_.listing_characteristic_type_id LEFT JOIN listing_characteristic_value_translation l6_ ON l5_.id = l6_.translatable_id WHERE l1_.locale = 'il' AND l3_.locale = 'il' AND l6_.locale = 'il';

to make a long story short I've discovered that I had the Hebrew translations missing from listing_characteristic_value_translation

once I've injected these directly into the DB -- I was able to see the Hebrew Characteristics.
INSERT INTO listing_characteristic_value_translation  (translatable_id, name, locale)
VALUES (1, 'ןכ', 'il');
INSERT INTO listing_characteristic_value_translation  (translatable_id, name, locale)
VALUES (2, 'אל', 'il');
INSERT INTO listing_characteristic_value_translation  (translatable_id, name, locale)
VALUES (3, 1, 'il');
INSERT INTO listing_characteristic_value_translation  (translatable_id, name, locale)
VALUES (4, 2, 'il');
INSERT INTO listing_characteristic_value_translation  (translatable_id, name, locale)
VALUES (5, 3, 'il');
INSERT INTO listing_characteristic_value_translation  (translatable_id, name, locale)
VALUES (6, '1 םאתומ ךרע', 'il');
INSERT INTO listing_characteristic_value_translation  (translatable_id, name, locale)
VALUES (7, '2 םאתומ ךרע', 'il');

hope that helps.

I  do see a UI quirk now

![image](https://user-images.githubusercontent.com/8761118/40585227-9b52b4be-61b7-11e8-9ded-00c1ea3e3814.png)

If I select a value from the Combo it then subsequently disappears  (see the top two characteristics in the screenshot missing the combo altogether?) 
they do update in the database because when I refresh the page they are shown correctly.

**Comment by handmade-it** [comment] 2018-05-27 18:56
@cypherfunk Thanks for your debugging. I can confirm that it works after the manual SQL edit. 

@cocolabssas Is there any way to define the values in the backend without having to edit the tables manually. For instance, what if like to have a third custom value or a quantity that is not from 1 to 3?

**Comment by giorgio654** [comment] 2018-05-28 11:35
Hi,
I had the same problem, a new pull request #178 has been supplied.

**Comment by giorgio654** [comment] 2018-05-28 12:37
The PR has been merged. :+1:

**Comment by jeanfrancois-glm** [comment] 2018-05-28 12:43
This issue is now fixed thanks to @giorgio654 . Thanks everybody for your help !

**Closed by jeanfrancois-glm** 2018-05-28 12:43 UTC
Labels: help wanted

**Comment by La-Meche** [comment] 2019-02-26 09:40
Any chance we can get the Hebrew translations? :-)
