### ISSUE TITLE
Docker demo / ListingVoter Critical error

### ISSUE THREAD

**Issue by bastien-wink** [Cocolabs-SAS/cocorico#366] opened 2019-02-24 12:27 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | [X]
| Feature request? | [ ]
| Support request? | [ ]

Using just de default docker image : 
docker run --name cocorico -ti -p 80:80 -p 3306:3306 -p 9001:9001 -p 27017:27017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -v `pwd`/tmp/mongo:/data/db -e HOST_UID=$UID cocolabs/cocorico

Then login to http://localhost/admin/login with super-admin@cocorico.rocks

`Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Warning: get_class() expects parameter 1 to be object, null given")." at /cocorico/src/Cocorico/SonataAdminBundle/Resources/views/standard_layout.html.twig line 197`

$listing is null at src/Cocorico/CoreBundle/Security/Voter/ListingVoter.php (line 54)

**Comment by cocolabssas** [comment] 2019-02-25 23:23
Hi @bastien-wink,

Indeed the issue is due to the fact that Cocorico docker linux distribution use now php 7.2 by default.
We are preparing a commit in Cocorico fixing this issue. It will be available tomorrow.

**Comment by cocolabssas** [comment] 2019-02-28 18:09
This issue is now fixed in commit 813dd0fdcecb133162a27e15efc2c2808607919a.

**Closed** 2019-03-04 17:24 UTC
Labels: bug
